services:
  postgres:
    image: postgres:16-alpine
    container_name: aetherstream_db
    environment:
      POSTGRES_USER: aether_admin
      POSTGRES_PASSWORD: HjKl0863
      POSTGRES_DB: aetherstream
    ports:
      # Maps port 5433 on your Mac to port 5432 inside the container
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
